### ISSUE TITLE
Problem compiling with KickC 0.8.4

### ISSUE THREAD

**Issue by JesperGravgaard** [markjfisher/kickc-benchmarks#1]
Hi Mark,

This is a copy of a private message on https://atariage.com/ 

I have made a new release of KickC - version 0.8.4. https://gitlab.com/camelot/kickc/-/releases

The benchmarks from https://github.com/markjfisher/kickc-benchmarks compiles without problem.

However, when I execute it it looks wrong and after a bunch of tests it seems to freeze with garbage text on screen after the MD5.

Maybe there is something wrong with the way I compile your suite - or maybe there is some issue with the new release.

Could you help me and test it out? I would like your suite to work before I announce the release on the Atari forum.

Kind regards,
Jesper Gravgaard

**Comment by markjfisher** [comment]
Glad you could sort the code out! Thanks for this.
